ArtifyConnector/ArtifiConnector/ViewModels/InstallationViewModel.cs
namespace ArtifiConnector.ViewModels
{
    public class InstallationViewModel
    {
        public string JavaScriptLibraryLink { get; set; }
    }
}

ArtifyConnector/ArtifiConnector/ViewModels/ProductsConfigurationViewModel.cs
namespace ArtifiConnector.ViewModels
{
    public class ProductsConfigurationViewModel
    {
        public string ButtonLabel { get; set; }
        public string Keyword { get; set; }
    }
}

ArtifyConnector/ArtifiConnector/Controllers/BigCommerceController.cs
using ArtifiConnector.Data;
using ArtifiConnector.Data.Models;
using ArtifiConnector.Extensions;
using ArtifiConnector.Models;
using ArtifiConnector.Properties;
using ArtifiConnector.ViewModels;
using ArtifiConnector.WebClients;
using ArtifiConnector.WebClients.Models;
using Ninject;
using System;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;

namespace ArtifiConnector.Controllers
{
    public class BigCommerceController : Controller
    {
        #region Injected Properties

        [Inject]
        public IBigCommerceWebClient BigCommerceWebClient { get; set; }

        [Inject]
        public IConfigurationRepository ConfigurationRepository { get; set; }

        [Inject]
        public ILogger Logger { get; set; }

        [Inject]
        public IMerchantRepository MerchantRepository { get; set; }

        #endregion Injected Properties

        public ActionResult ApplicationConfiguration()
        {
            try
            {
                var merchantId = int.Parse(Session["MerchantId"].ToString());
                var configuration = ConfigurationRepository.GetApplicationConfiguration(merchantId);

                return View("ApplicationConfiguration", configuration);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        public async Task<ActionResult> Auth([FromBody] AuthRequest request)
        {
            try
            {
                var receiveTokenRequest = new ReceiveTokenRequest
                {
                    ClientId = Settings.Default.ClientId,
                    ClientSecret = Settings.Default.ClientSecret,
                    Code = request.Code,
                    Scope = request.Scope,
                    RedirectUri = this.GetRequestUrl(),
                    Context = request.Context
                };

                var result = await BigCommerceWebClient.ReceiveTokenAsync(receiveTokenRequest);
                var merchant = MerchantRepository.Get(result.User.Id);

                if (merchant == null)
                {
                    var hash = GenerateHash();
                    var storeHash = result.Context.Split('/').Last();
                    merchant = new Merchant { Id = result.User.Id, AccessToken = result.AccessToken, StoreHash = storeHash, Hash = GenerateHash() };
                    MerchantRepository.Add(merchant);
                }
                else
                {
                    MerchantRepository.UpdateAccessToken(merchant.Id, result.AccessToken);
                }

                Session["MerchantId"] = merchant.Id;

                return ShowInstallationView(merchant.Id);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        public ActionResult Dashboard()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        public ActionResult DesignConfiguration()
        {
            try
            {
                var merchantId = int.Parse(Session["MerchantId"].ToString());

                var designConfiguration = ConfigurationRepository.GetDesignConfiguration(merchantId);

                return View("DesignConfiguration", designConfiguration);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        public ActionResult Load()
        {
            try
            {
                if (Request.QueryString.Count != 1)
                    throw new InvalidOperationException();

                var signedPayload = Request.QueryString[0];
                var store = BigCommerceDataProvider.ReadBigCommerceData(signedPayload, Settings.Default.ClientSecret);

                var merchant = MerchantRepository.Get(store.User.Id);

                if (merchant == null)
                    throw new InvalidOperationException();

                Session["MerchantId"] = merchant.Id;

                if (merchant.IsConfigured)
                    return View("Dashboard");
                else
                {
                    return ShowInstallationView(merchant.Id);
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        public ActionResult ProductsConfiguration(string keyword = null)
        {
            try
            {
                var merchantId = int.Parse(Session["MerchantId"].ToString());
                var configuration = ConfigurationRepository.GetDesignConfiguration(merchantId);

                var label = configuration.FirstOrDefault(x => x.Key == "CustomizedButtonLabel")?.Value;

                var viewModel = new ProductsConfigurationViewModel
                {
                    ButtonLabel = label ?? "Customizable",
                    Keyword = keyword
                };

                return View(viewModel);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        public ActionResult SetConfigured()
        {
            try
            {
                var merchantId = int.Parse(Session["MerchantId"].ToString());
                MerchantRepository.Configure(merchantId);
                return ApplicationConfiguration();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        public ActionResult Uninstall()
        {
            try
            {
                if (Request.QueryString.Count != 1)
                    throw new InvalidOperationException();

                var signedPayload = Request.QueryString[0];
                var store = BigCommerceDataProvider.ReadBigCommerceData(signedPayload, Settings.Default.ClientSecret);

                MerchantRepository.Remove(store.User.Id);
                return View();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }

        private string GenerateHash()
        {
            var input = Guid.NewGuid().ToString();
            MD5 md5 = MD5.Create();
            byte[] inputBytes = Encoding.ASCII.GetBytes(input);
            byte[] hash = md5.ComputeHash(inputBytes);

            StringBuilder sb = new StringBuilder();

            for (int i = 0; i < hash.Length; i++)
            {
                sb.Append(hash[i].ToString("X2"));
            }

            return sb.ToString();
        }

        private ActionResult ShowInstallationView(int merchantId)
        {
            try
            {
                var hash = MerchantRepository.GetMerchantHashById(merchantId);
                var scheme = Request.Url.Scheme;
                var authority = Request.Url.Authority;
                var url = Url.Content($"~/library/script/{hash}/bigcommerce.artifi.connector.js");
                var path = $"{scheme}://{authority}{url}";

                var viewModel = new InstallationViewModel
                {
                    JavaScriptLibraryLink = path
                };

                return View("Installation", viewModel);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex.ToString());
                throw;
            }
        }
    }
}

ArtifyConnector/ArtifiConnector/Views/BigCommerce/ApplicationConfiguration.cshtml
@model ArtifiConnector.Data.Models.ApplicationConfiguration

@{
    Layout = "~/Views/Shared/_ConfigurationLayout.cshtml";
}

<script type="text/javascript">

    function saveConfiguration() {

        var json = $('form').serializeObject();
        json.MerchantId = @Session["merchantId"]
        $.ajax({
            url: '/artificonnector/api/configuration/application',
            method: "POST",
            data: JSON.stringify(json),
        }).done(function() {
            configurationController.showSuccessBox("Application configuration has been updated.");
        }).fail(function(){
            configurationController.showFailBox("During application configuration save error has occured.");
        });

        return false;
    }

</script>

<div class="container">
    <div class="page-header">
        <h1>Application Configuration</h1>
    </div>

    <form onsubmit="return saveConfiguration()">
        <div class="form-group">
            <h3>General Application Configuration</h3>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.WebsiteId)
            @Html.TextBoxFor(x => x.WebsiteId, new { @class = "form-control", placeholder = "Please type your website id" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.WebApiClientKey)
            @Html.TextBoxFor(x => x.WebApiClientKey, new { @class = "form-control", placeholder = "Please type your web api client key" })
        </div>
        <button type="submit" class="btn btn-lg btn-primary">Save</button>
    </form>
</div>

ArtifyConnector/ArtifiConnector/Views/BigCommerce/Dashboard.cshtml
@{
    Layout = "~/Views/Shared/_ConfigurationLayout.cshtml";
}

<div class="container">
    <div class="page-header">
        <h1>Dashboard</h1>
    </div>

    <div class="jumbotron">
        <h1>Check our new features!</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
    </div>

    <p class="lead">Welcome in BigCommerce Artifi Connector configuration.</p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
        non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
</div>

ArtifyConnector/ArtifiConnector/Views/BigCommerce/DesignConfiguration.cshtml
@model IList<ArtifiConnector.Data.Models.DesignConfiguration>

@{
    Layout = "~/Views/Shared/_ConfigurationLayout.cshtml";
}

<script type="text/javascript">

    function saveConfiguration() {

        var array = $('form').serializeDesignConfiguration();

        var json = {array:array, merchantId:@Session["merchantId"] };

        $.ajax({
            url: '/artificonnector/api/configuration/design',
            method: "POST",
            data: JSON.stringify(json),
        }).done(function() {
            configurationController.showSuccessBox("Design configuration has been updated.");
        }).fail(function(){
            configurationController.showFailBox("During design configuration save error has occured.");
        });

        return false;
    }

</script>

<div class="container">
    <div class="page-header">
        <h1>Design Configuration</h1>
    </div>

    <form onsubmit="return saveConfiguration()">
        <div class="form-group">
            <h3>Buttons Design Configuration</h3>
        </div>
        <div class="form-group">
            @for (int i = 0; i < Model.Count(); i++)
            {
                @Html.HiddenFor(x => x[i].Id)
                @Html.LabelFor(x => x[i].DisplayName)
                @Html.TextBoxFor(x => x[i].Value, new { @class = "form-control", placeholder = $"Please type your { Model[i].DisplayName.ToLower()}" })
            }
        </div>
        <button type="submit" class="btn btn-lg btn-primary">Save</button>
    </form>

</div>

ArtifyConnector/ArtifiConnector/Views/BigCommerce/Load.cshtml
@{
    ViewBag.Title = "Load";
}

<h2>Please configure products</h2>

ArtifyConnector/ArtifiConnector/Views/BigCommerce/ProductsConfiguration.cshtml
@model ArtifiConnector.ViewModels.ProductsConfigurationViewModel

@{
    Layout = "~/Views/Shared/_ConfigurationLayout.cshtml";
}

@functions {
    public string GetParametrizedUrl(string url)
    {
        if (string.IsNullOrWhiteSpace(Model.Keyword))
            return url;

        return url + "?keyword=" + Model.Keyword;
    }
}

@section Scripts
{
    @Scripts.Render("~/bundles/dataTables")
    @Scripts.Render("~/bundles/dataTablesBootstrap")
    @Styles.Render("~/content/dataTablesArtifi")

    <script type="text/javascript">

        var label = "@Model.ButtonLabel";

        var table = null;

        function initializeDataTable(count,data)        {
            table = $('#productsTable').DataTable({
                "processing":true,
                "serverSide": true,
                "deferLoading": count,
                "pageLength":20,
                "ajax": {
                    "url": '@GetParametrizedUrl("/artificonnector/api/products")',
                    "headers":{"authorization": @Session["merchantId"]},
                    "data" : function(d){
                        var page = (d.start/d.length)+1;
                        d.page = page;
                    }
                },
                "data":data,
                "language": {
                    "paginate": {
                        "next": "&raquo;",
                        "previous": "&laquo;"
                    }
                },
                "dom":  "<'row'<'col-sm-6'><'col-sm-6'l>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-5'p><'col-sm-7'i>>",
                "ordering": false,
                "info": false,
                "columns": [
                    {
                        "data": null,
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "data": "Sku",
                        "title": "Product SKU"
                    },
                    {
                        "data": "Name",
                        "title": "Product Name"
                    },
                    {
                        "data": null,
                        "title": "Action"
                    },
                    {
                        "data": "IsSet",
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "data": "Id",
                        "visible": false,
                        "searchable": false
                    },
                ],
                "columnDefs": [{
                    "render": function (data, type, row) {
                        var labelText = "";
                        var buttonStyle= "";
                        if (data["IsSet"]) {
                            labelText = "Unset As " + label;
                            buttonStyle = "btn-success";
                        }
                        else {
                            labelText = "Set As " + label;
                            buttonStyle = "btn-default";
                        }
                        return "<a id='link" + data["Id"] + "' class='btn "+buttonStyle+"' role='button' onclick='changeTitle(" + data["Id"] + ", &quot;" + data["Name"] + "&quot;, &quot;" + data["Sku"] + "&quot;, this);'>" + labelText + "</a>";
                    },
                    "targets": 3
                }]
            });
        }

        $(document).ready(function () {

            showLoading();

            $.ajax({
                url: '@GetParametrizedUrl("/artificonnector/api/products/count")',
                headers:{"authorization": @Session["merchantId"]},
                method: "GET"
            }).done(function (countResult){
                var count = countResult.count;

                $.ajax({
                    url: '@GetParametrizedUrl("/artificonnector/api/products")',
                    headers:{"authorization": @Session["merchantId"]},
                    method: "GET",
                }).done(function(result) {
                    if(result!=null)
                        initializeDataTable(count, result.data);
                    hideLoading();
                }).fail(function(data) {
                    hideLoading();
                });
            });
        });

        function changeTitle(id, name, sku, button) {
            if (button.text === "Set As " + label) {
                addProduct(id, name, sku, button);
            }
            else {
                deleteProduct(id, name, sku, button);
            }
        }

        function addProduct(id, name, sku, button) {
            showLoading();

            var json = { id:id, sku:sku, merchantId : @Session["merchantId"] };
            var link = $("#link" + id);

            $.ajax({
                url: '/artificonnector/api/products',
                method: "POST",
                data: JSON.stringify(json)
            }).done(function() {
                configurationController.showSuccessBox("Product " + name + " has been added.");
                hideLoading();
                button.text = "Unset As " + label;
                link.removeClass("btn-default").addClass("btn-success");
            }).fail(function(){
                configurationController.showFailBox("During product add error has occured.");
                hideLoading();
            });
        }

        function deleteProduct(id, name, sku, button) {
            showLoading();

            var json = { id:id, sku:sku, merchantId : @Session["merchantId"] };
            var link = $("#link" + id);

            $.ajax({
                url: '/artificonnector/api/products',
                method: "DELETE",
                data: JSON.stringify(json)
            }).done(function() {
                configurationController.showSuccessBox("Product " + name + " has been deleted.");
                hideLoading();
                button.text = "Set As " + label;
                link.removeClass("btn-success").addClass("btn-default");
            }).fail(function(){
                configurationController.showFailBox("During product delete error has occured.");
                hideLoading();
            });
        }

        function showLoading(){
            $("#productsTable").hide();
            $("#productsTableSearch").hide();
            $("#loader").show();
        }

        function hideLoading(){
            $("#loader").hide();
            $("#productsTable").show();
            $("#productsTableSearch").show();
        }
    </script>
}

<div class="container">
    <div class="page-header">
        <h1>Products Configuration</h1>
    </div>
    <img id="loader" src="~/images/loading_icon_photo.gif" style="display: block;margin: 0 auto;">

    <div id="productsTableSearch" class="container-fluid search-products">

        @using (Html.BeginForm("ProductsConfiguration", "BigCommerce", FormMethod.Get, new { @class = "form-inline" }))
            {
            <div class="form-group">
                @Html.TextBoxFor(x => x.Keyword, new { @class = "form-control", placehold = "Search products by name / sku" })
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        }
    </div>

    <table id="productsTable" class="table table-striped dt-responsive" style="display:none; width:100%">
        <thead>
            <tr>
                <th><input type="checkbox"></th>
                <th>Id</th>
                <th>Sku</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>

ArtifyConnector/ArtifiConnector/Views/BigCommerce/Uninstall.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Uninstall</title>
</head>
<body>
    <div>
    </div>
</body>
</html>